# Generated by Django 5.2 on 2025-04-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
